apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        mohammadimran0186/B-N-tsk-: true
        mohammadimran0186/golang-jx-demo-app: true
        mohammadimran0186/jenkinsx: true
        mohammadimran0186/jenkinsx-node-app: true
        mohammadimran0186/jx-golang-demo2: true
        mohammadimran0186/node-http-sample: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        mohammadimran0186/B-N-tsk-: merge
        mohammadimran0186/golang-jx-demo-app: merge
        mohammadimran0186/jenkinsx: merge
        mohammadimran0186/jenkinsx-node-app: merge
        mohammadimran0186/jx-golang-demo2: merge
        mohammadimran0186/node-http-sample: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - mohammadimran0186/jenkinsx
        - mohammadimran0186/B-N-tsk-
        - mohammadimran0186/golang-jx-demo-app
        - mohammadimran0186/jenkinsx-node-app
        - mohammadimran0186/jx-golang-demo2
        - mohammadimran0186/node-http-sample
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - mohammadimran0186/jenkinsx
        - mohammadimran0186/B-N-tsk-
        - mohammadimran0186/golang-jx-demo-app
        - mohammadimran0186/jenkinsx-node-app
        - mohammadimran0186/jx-golang-demo2
        - mohammadimran0186/node-http-sample
      target_url: http://lighthouse-jx.192.168.49.2.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
